- name: app-setup
  ansible.builtin.import_role:
    name: common # role name
    tasks_from: app-setup

- name: nodejs-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup

- name: mongodb-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemd-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: deployemnt
  ansible.builtin.import_role:
    name: common
    tasks_from: deployment



