- name: "stop {{component}}"
  tags:
  - deployemnt
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployemnt
  ansible.builtin.file:
    path: "/app"
    state: absent
    

