- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the categories count
  ansible.builtin.command:  mongo --host mongodb.daws80.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: component == "catalogue"

- name: get the users count
  ansible.builtin.command:  mongo --host mongodb.daws80.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: component == "user"

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

- name: load {{component}} data
  ansible.builtin.command: mongo --host mongodb.daws80.online < /app/schema/{{componet}}.js
  when: product_count.stdout == "0" # keep double quotes
  

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.daws80.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes

  