- name: Copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: deamon reload and start
  ansible.builtin.systemd_service:
    deamon_reload: true

- name: start and enable catalogue
  ansible.builtin.service:
    name: restarted
    enabled: yes