- name: app-setup
  ansible.builtin.import_role:
    name: common # which is to be import
    tasks_from: app-setup # which is file in common role

- name: nodejs setup
  ansible.builtin.import_role:
    name: common # which is to be import
    tasks_from: nodejs # which is file in common role no need extensions

- name: mongodb-setup
  ansible.builtin.import_role:
    name: common # which is to be import
    tasks_from: mongodbsetup

- name: systemctl-setup
  ansible.builtin.import_role:
    name: common # which is to be import
    tasks_from: systemd
